from PyQt5 import QtCore, QtGui, QtWidgets
from conexion.conexion_bd import database

class Ui_vista_principal(object):
    def setupUi(self, vista_principal):
        vista_principal.setObjectName("vista_principal")
        vista_principal.resize(902, 524)
        self.centralwidget = QtWidgets.QWidget(vista_principal)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(159, -1, 361, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.toolbar_veterinaria = QtWidgets.QWidget(self.centralwidget)
        self.toolbar_veterinaria.setGeometry(QtCore.QRect(-1, -1, 161, 561))
        self.toolbar_veterinaria.setObjectName("toolbar_veterinaria")
        self.btn_mascotas = QtWidgets.QPushButton(self.toolbar_veterinaria)
        self.btn_mascotas.setGeometry(QtCore.QRect(0, 0, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_mascotas.setFont(font)
        self.btn_mascotas.setObjectName("btn_mascotas")
        self.btn_cliente = QtWidgets.QPushButton(self.toolbar_veterinaria)
        self.btn_cliente.setGeometry(QtCore.QRect(0, 80, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_cliente.setFont(font)
        self.btn_cliente.setObjectName("btn_cliente")
        self.btn_veterinario = QtWidgets.QPushButton(self.toolbar_veterinaria)
        self.btn_veterinario.setGeometry(QtCore.QRect(0, 160, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_veterinario.setFont(font)
        self.btn_veterinario.setObjectName("btn_veterinario")
        self.btn_reporte = QtWidgets.QPushButton(self.toolbar_veterinaria)
        self.btn_reporte.setGeometry(QtCore.QRect(0, 240, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_reporte.setFont(font)
        self.btn_reporte.setObjectName("btn_reporte")
        self.btn_grafica = QtWidgets.QPushButton(self.toolbar_veterinaria)
        self.btn_grafica.setGeometry(QtCore.QRect(0, 320, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_grafica.setFont(font)
        self.btn_grafica.setObjectName("btn_grafica")
        self.btn_grafica_2 = QtWidgets.QPushButton(self.toolbar_veterinaria)
        self.btn_grafica_2.setGeometry(QtCore.QRect(0, 400, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_grafica_2.setFont(font)
        self.btn_grafica_2.setObjectName("btn_grafica_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(520, 0, 381, 481))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 387, 271))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fr_mascota = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.fr_mascota.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_mascota.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_mascota.setObjectName("fr_mascota")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.fr_mascota)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cmb_dia_cliente = QtWidgets.QComboBox(self.fr_mascota)
        self.cmb_dia_cliente.setObjectName("cmb_dia_cliente")
        self.gridLayout_5.addWidget(self.cmb_dia_cliente, 4, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.fr_mascota)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_5.addWidget(self.lineEdit_10, 5, 1, 1, 3)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.fr_mascota)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_5.addWidget(self.lineEdit_11, 7, 1, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.fr_mascota)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.fr_mascota)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 3, 0, 1, 2)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.fr_mascota)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_5.addWidget(self.lineEdit_9, 3, 2, 1, 2)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.fr_mascota)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_5.addWidget(self.lineEdit_8, 2, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.fr_mascota)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.fr_mascota)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 6, 0, 1, 1)
        self.lbl_id_cliente = QtWidgets.QLabel(self.fr_mascota)
        self.lbl_id_cliente.setObjectName("lbl_id_cliente")
        self.gridLayout_5.addWidget(self.lbl_id_cliente, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.fr_mascota)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.fr_mascota)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 4, 0, 1, 1)
        self.cmb_year_cliente = QtWidgets.QComboBox(self.fr_mascota)
        self.cmb_year_cliente.setObjectName("cmb_year_cliente")
        self.gridLayout_5.addWidget(self.cmb_year_cliente, 4, 3, 1, 1)
        self.cmb_mes_cliente = QtWidgets.QComboBox(self.fr_mascota)
        self.cmb_mes_cliente.setObjectName("cmb_mes_cliente")
        self.gridLayout_5.addWidget(self.cmb_mes_cliente, 4, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.fr_mascota)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_5.addWidget(self.lineEdit_7, 1, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.fr_mascota)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 5, 0, 1, 1)
        self.sp_no_calle_cliente = QtWidgets.QSpinBox(self.fr_mascota)
        self.sp_no_calle_cliente.setObjectName("sp_no_calle_cliente")
        self.gridLayout_5.addWidget(self.sp_no_calle_cliente, 6, 1, 1, 3)
        self.label = QtWidgets.QLabel(self.fr_mascota)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.fr_mascota)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 8, 0, 1, 1)
        self.txt_correo_cliente = QtWidgets.QLineEdit(self.fr_mascota)
        self.txt_correo_cliente.setObjectName("txt_correo_cliente")
        self.gridLayout_5.addWidget(self.txt_correo_cliente, 8, 1, 1, 3)
        self.gridLayout_2.addWidget(self.fr_mascota, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setGeometry(QtCore.QRect(-1, -1, 381, 141))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.lbl_id_mascota = QtWidgets.QLabel(self.frame_2)
        self.lbl_id_mascota.setObjectName("lbl_id_mascota")
        self.gridLayout_6.addWidget(self.lbl_id_mascota, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 1, 0, 1, 1)
        self.txt_nombre_mascota = QtWidgets.QLineEdit(self.frame_2)
        self.txt_nombre_mascota.setObjectName("txt_nombre_mascota")
        self.gridLayout_6.addWidget(self.txt_nombre_mascota, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 2, 0, 1, 1)
        self.cmb_tipo_mascota = QtWidgets.QComboBox(self.frame_2)
        self.cmb_tipo_mascota.setObjectName("cmb_tipo_mascota")
        self.gridLayout_6.addWidget(self.cmb_tipo_mascota, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 3, 0, 1, 1)
        self.sp_peso_mascota = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.sp_peso_mascota.setObjectName("sp_peso_mascota")
        self.gridLayout_6.addWidget(self.sp_peso_mascota, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 4, 0, 1, 1)
        self.lbl_id_mascota_cliente = QtWidgets.QLabel(self.frame_2)
        self.lbl_id_mascota_cliente.setObjectName("lbl_id_mascota_cliente")
        self.gridLayout_6.addWidget(self.lbl_id_mascota_cliente, 4, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_3 = QtWidgets.QFrame(self.page_3)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 371, 291))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cmb_dia_veterinario = QtWidgets.QComboBox(self.frame_3)
        self.cmb_dia_veterinario.setObjectName("cmb_dia_veterinario")
        self.gridLayout_3.addWidget(self.cmb_dia_veterinario, 4, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 0, 1, 1)
        self.txt_primer_veterinario = QtWidgets.QLineEdit(self.frame_3)
        self.txt_primer_veterinario.setObjectName("txt_primer_veterinario")
        self.gridLayout_3.addWidget(self.txt_primer_veterinario, 2, 1, 1, 3)
        self.label_21 = QtWidgets.QLabel(self.frame_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 3, 0, 1, 1)
        self.txt_colonia_veterinario = QtWidgets.QLineEdit(self.frame_3)
        self.txt_colonia_veterinario.setObjectName("txt_colonia_veterinario")
        self.gridLayout_3.addWidget(self.txt_colonia_veterinario, 7, 1, 1, 3)
        self.txt_segundo_veterinario = QtWidgets.QLineEdit(self.frame_3)
        self.txt_segundo_veterinario.setObjectName("txt_segundo_veterinario")
        self.gridLayout_3.addWidget(self.txt_segundo_veterinario, 3, 1, 1, 3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 8, 2, 1, 2)
        self.txt_nombre_veterinario = QtWidgets.QLineEdit(self.frame_3)
        self.txt_nombre_veterinario.setObjectName("txt_nombre_veterinario")
        self.gridLayout_3.addWidget(self.txt_nombre_veterinario, 1, 1, 1, 3)
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 4, 0, 1, 1)
        self.txt_calle_veterinario = QtWidgets.QLineEdit(self.frame_3)
        self.txt_calle_veterinario.setObjectName("txt_calle_veterinario")
        self.gridLayout_3.addWidget(self.txt_calle_veterinario, 5, 1, 1, 3)
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 6, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 7, 0, 1, 1)
        self.cmb_mes_veterinario = QtWidgets.QComboBox(self.frame_3)
        self.cmb_mes_veterinario.setObjectName("cmb_mes_veterinario")
        self.gridLayout_3.addWidget(self.cmb_mes_veterinario, 4, 2, 1, 1)
        self.lbl_id_veterinario = QtWidgets.QLabel(self.frame_3)
        self.lbl_id_veterinario.setObjectName("lbl_id_veterinario")
        self.gridLayout_3.addWidget(self.lbl_id_veterinario, 0, 1, 1, 3)
        self.cmb_year_veterinario = QtWidgets.QComboBox(self.frame_3)
        self.cmb_year_veterinario.setObjectName("cmb_year_veterinario")
        self.gridLayout_3.addWidget(self.cmb_year_veterinario, 4, 3, 1, 1)
        self.sp_no_calle_veterinario = QtWidgets.QSpinBox(self.frame_3)
        self.sp_no_calle_veterinario.setObjectName("sp_no_calle_veterinario")
        self.gridLayout_3.addWidget(self.sp_no_calle_veterinario, 6, 1, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 8, 0, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 9, 0, 1, 2)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 9, 2, 1, 2)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.frame_4 = QtWidgets.QFrame(self.page_4)
        self.frame_4.setGeometry(QtCore.QRect(-1, -1, 381, 341))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_25 = QtWidgets.QLabel(self.frame_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 0, 0, 1, 1)
        self.lbl_id_veterinario_servicio = QtWidgets.QLabel(self.frame_4)
        self.lbl_id_veterinario_servicio.setObjectName("lbl_id_veterinario_servicio")
        self.gridLayout_4.addWidget(self.lbl_id_veterinario_servicio, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 1, 0, 1, 1)
        self.lbl_id_mascota_servicio = QtWidgets.QLabel(self.frame_4)
        self.lbl_id_mascota_servicio.setObjectName("lbl_id_mascota_servicio")
        self.gridLayout_4.addWidget(self.lbl_id_mascota_servicio, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_4)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 2, 0, 1, 1)
        self.cmb_tipo_servicio = QtWidgets.QComboBox(self.frame_4)
        self.cmb_tipo_servicio.setObjectName("cmb_tipo_servicio")
        self.gridLayout_4.addWidget(self.cmb_tipo_servicio, 2, 1, 1, 2)
        self.label_28 = QtWidgets.QLabel(self.frame_4)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 3, 0, 1, 1)
        self.cmb_dia_servicio = QtWidgets.QComboBox(self.frame_4)
        self.cmb_dia_servicio.setObjectName("cmb_dia_servicio")
        self.gridLayout_4.addWidget(self.cmb_dia_servicio, 3, 1, 1, 1)
        self.cmb_mes_servicio = QtWidgets.QComboBox(self.frame_4)
        self.cmb_mes_servicio.setObjectName("cmb_mes_servicio")
        self.gridLayout_4.addWidget(self.cmb_mes_servicio, 3, 2, 1, 1)
        self.cmb_year_servicio = QtWidgets.QComboBox(self.frame_4)
        self.cmb_year_servicio.setObjectName("cmb_year_servicio")
        self.gridLayout_4.addWidget(self.cmb_year_servicio, 3, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_4)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 4, 0, 1, 1)
        self.cmb_dia_servicio_s = QtWidgets.QComboBox(self.frame_4)
        self.cmb_dia_servicio_s.setObjectName("cmb_dia_servicio_s")
        self.gridLayout_4.addWidget(self.cmb_dia_servicio_s, 4, 1, 1, 1)
        self.cmb_mes_servicio_s = QtWidgets.QComboBox(self.frame_4)
        self.cmb_mes_servicio_s.setObjectName("cmb_mes_servicio_s")
        self.gridLayout_4.addWidget(self.cmb_mes_servicio_s, 4, 2, 1, 1)
        self.cmb_tipo_servicio_s = QtWidgets.QComboBox(self.frame_4)
        self.cmb_tipo_servicio_s.setObjectName("cmb_tipo_servicio_s")
        self.gridLayout_4.addWidget(self.cmb_tipo_servicio_s, 4, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_4)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 5, 0, 1, 1)
        self.txt_servicio = QtWidgets.QPlainTextEdit(self.frame_4)
        self.txt_servicio.setObjectName("txt_servicio")
        self.gridLayout_4.addWidget(self.txt_servicio, 5, 1, 1, 3)
        self.stackedWidget.addWidget(self.page_4)
        vista_principal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(vista_principal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 20))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        vista_principal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(vista_principal)
        self.statusbar.setObjectName("statusbar")
        vista_principal.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuArchivo.menuAction())

        #acciones de botones
        self.btn_mascotas.clicked.connect(self.cambiar_pagina)
        self.btn_cliente.clicked.connect(self.cambiar_pagina1)
        self.btn_veterinario.clicked.connect(self.cambiar_pagina2)
        self.btn_reporte.clicked.connect(self.cambiar_pagina3)
        self.btn_grafica.clicked.connect(self.prueba_database)

        self.retranslateUi(vista_principal)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(vista_principal)

    def retranslateUi(self, vista_principal):
        _translate = QtCore.QCoreApplication.translate
        vista_principal.setWindowTitle(_translate("vista_principal", "Clinica"))
        self.btn_mascotas.setText(_translate("vista_principal", "Mascotas"))
        self.btn_cliente.setText(_translate("vista_principal", "Cliente"))
        self.btn_veterinario.setText(_translate("vista_principal", "veterinario"))
        self.btn_reporte.setText(_translate("vista_principal", "Reportes"))
        self.btn_grafica.setText(_translate("vista_principal", "graficas"))
        self.btn_grafica_2.setText(_translate("vista_principal", "Salida"))
        self.label_8.setText(_translate("vista_principal", "Colonia"))
        self.label_4.setText(_translate("vista_principal", "Segundo Apellido"))
        self.label_2.setText(_translate("vista_principal", "Nombre"))
        self.label_7.setText(_translate("vista_principal", "No Calle"))
        self.lbl_id_cliente.setText(_translate("vista_principal", "TextLabel"))
        self.label_3.setText(_translate("vista_principal", "Primer Apellido"))
        self.label_5.setText(_translate("vista_principal", "Fecha"))
        self.label_6.setText(_translate("vista_principal", "Calle"))
        self.label.setText(_translate("vista_principal", "ID Cliente"))
        self.label_33.setText(_translate("vista_principal", "Correo Electronico"))
        self.label_10.setText(_translate("vista_principal", "ID Mascota"))
        self.lbl_id_mascota.setText(_translate("vista_principal", "TextLabel"))
        self.label_11.setText(_translate("vista_principal", "Nombre"))
        self.label_12.setText(_translate("vista_principal", "Tipo"))
        self.label_13.setText(_translate("vista_principal", "Peso"))
        self.label_14.setText(_translate("vista_principal", "ID cliente"))
        self.lbl_id_mascota_cliente.setText(_translate("vista_principal", "TextLabel"))
        self.label_18.setText(_translate("vista_principal", "Primer apellido"))
        self.label_21.setText(_translate("vista_principal", "Calle"))
        self.label_19.setText(_translate("vista_principal", "Segundo apellido"))
        self.pushButton_2.setText(_translate("vista_principal", "PushButton"))
        self.label_20.setText(_translate("vista_principal", "Fecha nacimiento"))
        self.label_16.setText(_translate("vista_principal", "ID Veterinario"))
        self.label_22.setText(_translate("vista_principal", "No Calle"))
        self.label_17.setText(_translate("vista_principal", "Nombre"))
        self.label_23.setText(_translate("vista_principal", "Colonia"))
        self.lbl_id_veterinario.setText(_translate("vista_principal", "TextLabel"))
        self.pushButton.setText(_translate("vista_principal", "PushButton"))
        self.pushButton_3.setText(_translate("vista_principal", "PushButton"))
        self.pushButton_4.setText(_translate("vista_principal", "PushButton"))
        self.label_25.setText(_translate("vista_principal", "ID Veterinario"))
        self.lbl_id_veterinario_servicio.setText(_translate("vista_principal", "TextLabel"))
        self.label_26.setText(_translate("vista_principal", "ID Mascota"))
        self.lbl_id_mascota_servicio.setText(_translate("vista_principal", "TextLabel"))
        self.label_27.setText(_translate("vista_principal", "Tipo Servicio"))
        self.label_28.setText(_translate("vista_principal", "Fecha Entrada"))
        self.label_29.setText(_translate("vista_principal", "Fecha Salida"))
        self.label_30.setText(_translate("vista_principal", "Diagnostico"))
        self.menuArchivo.setTitle(_translate("vista_principal", "Archivo"))

    def cambiar_pagina(self):
        self.stackedWidget.setCurrentIndex(1)
    
    def cambiar_pagina1(self):
        self.stackedWidget.setCurrentIndex(0)
    
    def cambiar_pagina2(self):
        self.stackedWidget.setCurrentIndex(2)
    
    def cambiar_pagina3(self):
        self.stackedWidget.setCurrentIndex(3)
        
    def prueba_database(self):
        print("hola ")
        x = database()
        x.all_users()
